- name: Re-enable the nodes
  hosts: "{{ hosts }}"
  connection: local

      - name: Add members back into gw_pool
        bigip_pool_member:
            server: "{{ inventory_hostname }}"
            user: "{{username}}"
            password: "{{password}}"
            state: "present"
            host: "{{ item }}"
            pool: "gw_pool"
            port: "80"
            validate_certs: "false"
        with_items:
            - generic_web01
